name: dbs2

# TODO komentáře

services:

  dbs2-postgres:
    image: postgres:17-alpine
    container_name: dbs2-postgres
    environment:
      - PG_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "10.8.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  dbs2:
    container_name: dbs2
    build:
      context: .
    restart: always
    depends_on:
      - dbs2-postgres
    ports:
       - "127.0.0.1:8081:8081"
    environment:
      - GIN_MODE=${GIN_MODE}
      - APP_URL=${APP_URL}
      - SWAGGER=${SWAGGER}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PW=${ADMIN_PW}
      - POSTGRES_USER=${PG_USER}
      - PG_USER=${PG_USER}
      - PG_PW=${PG_PW}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - ACCESS_TOKEN_LIFESPAN=${ACCESS_TOKEN_LIFESPAN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}

volumes:
  postgres_data:
