name: dbs2

services:

  # PostgreSQL databáze
  dbs2-postgres:
    image: postgres:17-alpine # PostgreSQL obraz založený na Alpine Linuxu
    container_name: dbs2-postgres
    environment:
      # Konfigurace PostgreSQL
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
    ports:
      # Mapování portu z kontejneru na hostitelský port (kvůli připojení k databázi z GUI klienta)
      - "10.8.0.1:5432:5432"
    volumes:
      # Databázové úložiště
      - postgres_data:/var/lib/postgresql/data
      # Časové pásmo
      - /etc/localtime:/etc/localtime:ro
    restart: always

  # Backend
  dbs2:
    container_name: dbs2
    # Sestavení obrazu při rozběhnutí compose
    build:
      context: .
    restart: always
    # Závislost na databázi
    depends_on:
      - dbs2-postgres
    ports:
      # Mapování portu z kontejneru na hostitelský port (kvůli reverzní proxy)
       - "127.0.0.1:8081:8081"
    volumes:
      # Adresář pro ukládání obrázků
      - dbs2_uploads:/app/uploads
      # Časové pásmo
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Konfigurace aplikace
      - GIN_MODE=${GIN_MODE}
      - APP_URL=${APP_URL}
      - SWAGGER=${SWAGGER}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PW=${ADMIN_PW}
      - POSTGRES_USER=${PG_USER}
      - PG_USER=${PG_USER}
      - PG_PW=${PG_PW}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - ACCESS_TOKEN_LIFESPAN=${ACCESS_TOKEN_LIFESPAN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
  
  # Kontejner pro zálohování databáze (https://github.com/jsfraz/mega-backuper)
  dbs2-mega-backuper:
    image: ghcr.io/jsfraz/mega-backuper:latest
    container_name: dbs2-mega-backuper
    restart: always
    depends_on:
      - dbs2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backuper.json:/app/backuper.json
      - dbs2_uploads:/tmp/uploads

volumes:
  postgres_data:
  dbs2_uploads:
